### ISSUE TITLE
Code generator

### ISSUE THREAD

**Issue by nilshelmig** [miniBill/elm-bare#1]
Hello :wave: 
Nice implementation by using the well known Codec API :smiley: 

Are there any plans on code generation out of BARE schemas? Could be a little JS script which would be available over npm. As a base the [JS implementation](https://git.sr.ht/~kiito/bare-js/tree/master/item/converter) could be used.

**Comment by miniBill** [comment]
Ok, working on this today

**Comment by miniBill** [comment]
Spec parser is done, now I 'just" need to write the generator

**Comment by miniBill** [comment]
Work in progress, it can already generate some stuff https://github.com/miniBill/elm-bare-generator

**Comment by miniBill** [comment]
It's reasonably done, try it!
